### ISSUE TITLE
Compatibility with other optimizations

### ISSUE THREAD

**Issue by Andrey36652** [sihyun-yu/REPA#1]
Hello, I appreciate your work. The idea is elegant and simple yet powerful. And your work contains a lot of implementation details.
How do you think, can your speedups be combined with findings of this work https://arxiv.org/abs/2407.15811 to obtain even more gains in training efficiency?

**Comment by sihyun-yu** [comment]
Hi, thanks for your interest in our work! I haven't tried it, but I think it will be a very interesting possible direction - as our regularization is designed in "patch-wise" manner, such masking strategy can be naturally incorporated with REPA.
