### ISSUE TITLE
How to calculate similarity, when the feature shape is different?

### ISSUE THREAD

**Issue by zyx1213271098** [sihyun-yu/REPA#11]

**Comment by sihyun-yu** [comment]
You can measure the alignment between two features (which have different hidden dims) computed from two models. The important thing is that the features should be computed from the same dataset. See [here)(https://github.com/minyoungg/platonic-rep/blob/main/README.md) for details

**Comment by zyx1213271098** [comment]
How to align when the number of tokens is different？

**Comment by sihyun-yu** [comment]
We use globally pooled representations.

**Comment by Jourdelune** [comment]
Do you mean using AvgPool from PyTorch (e.g., https://pytorch.org/docs/stable/generated/torch.nn.AvgPool1d.html)? I want to apply this regularization technique to a transformer model, so the size of the hidden space changes depending on the sequence length. For the feature dimension, I can downsample using a Linear layer, but I am not sure how to handle the sequence length dimension. For example, calculating the cosine similarity between a tensor a with the shape [1, 512, 314] and a tensor b with the shape [1, 512, 3524], where the shapes are [batch size, feature_dim, seq_len].
