### ISSUE TITLE
Apply REPA to other projects

### ISSUE THREAD

**Issue by 11whitewater** [sihyun-yu/REPA#14]
Hi, thank you very much for your great contribution, if I want to apply the REPA framework to the training of other large diffusion models (such as StableSR), how should I do it? Could you please give me some advice?

**Comment by sihyun-yu** [comment]
Hi, we haven't tried due to lack of resources but it will be certainly an interesting direction. I think REPA can be applied to other conditional diffusion models (like t2i) in a very similar manner particularly for diffusion transformer architecture.
