### ISSUE TITLE
Apply REPA to x-ray image domain

### ISSUE THREAD

**Issue by pILLOW-1** [sihyun-yu/REPA#15]
Hi, @sihyun-yu, great work!
Should I modify any component of the current framework if I want to apply REPA to a different image domain, like X-ray?

**Comment by sihyun-yu** [comment]
Hi, I haven't tried, but you might need a fine-tuned (or trained) visual representation with X-ray data. But I think existing visual encoders would provide a meaningful improvement!

**Comment by pILLOW-1** [comment]
OK, Thanks. One more question, if I want to apply REPA to a diffusion UNet rather than a diffusion transformer, should I change the position of the projection head? Have you done experiments on a diffusion UNet like that?
