### ISSUE TITLE
feature space gap between SiT and DINOv2

### ISSUE THREAD

**Issue by bluekingsong** [sihyun-yu/REPA#16]
Hi,  I find that the feature input of SiT is VAE latent while input of DINOv2 model is raw image, is it a problem for  representation alignment?

**Comment by sihyun-yu** [comment]
VAE latent is just a compressed latent image (which has very similar properties to image pixels), and the notion of "representation" in our paper is a latent vector that contains semantics (e.g., DINOv2, which you mentioned). So it is not a problem for representation alignment.
