### ISSUE TITLE
Feature alignment performs on other layers.

### ISSUE THREAD

**Issue by Dyb3438** [sihyun-yu/REPA#17]
Hi @sihyun-yu,

Thanks for the interesting work. After reading the paper and starting the experiments, I wonder why the REPA perform the feature alignment only on the 8th layer (e.g. SiT-XL/2) nor on the other layers (e.g. the 20th layer, the figure 2(b) shows that in SiT-XL/2 without feature alignment module, the 20th layer has the most similar feature distribution with DINOv2-g).

Also, I haven't found (probably my oversight) any ablation study on the feature alignment performed on the other SiT layers. 

If you could answer these questions or give me some insights, I'd really appreciate it!

**Comment by sihyun-yu** [comment]
Hi, please check Table 2, the paper, and the "Alignment depth" paragraph on page 8.

> We find that regularizing only the first few layers (e.g., 8) in training is sufficient, as indicated by the linear probing results in Table 2. Interestingly, limiting regularization to the first few layers further enhances generation performance (e.g., adding REPA to layers 6 or 8 yields the best results). We hypothesize that this enables the remaining layers to concentrate on capturing high-frequency details, building on a strong representation. In future experiments, we apply REPA to the first 8 layers.

**Comment by xesdiny** [comment]
@sihyun-yu Hi, according to the paper, can we infer that for single layer alignment, as the model scale increases, the layer id selected for alignment needs to be larger?
Also, for multi-layer align operations, is it appropriate to use a common MLP or construct each layer id independently?
