### ISSUE TITLE
Extract feature from DINOv2 with resolution 448 * 448 or downsample feature of DiT, which is better?

### ISSUE THREAD

**Issue by Luciennnnnnn** [sihyun-yu/REPA#18]
Hi, I'm wondering if i want to work with image with resolution 512 * 512. How should I align resolution of DINOv2 and DiT? Extract feature from DINOv2 with resolution 448 * 448 or downsample feature of DiT from 32 * 32 to 16 * 16, which is better?

**Comment by sihyun-yu** [comment]
Hi, thanks for your interest. I haven't tried, but I expect 448x448 to be a better choice as it might contain more high-frequency details.
