### ISSUE TITLE
Will the authors release the pretrained checkpoint on ImageNet?

### ISSUE THREAD

**Issue by Dyb3438** [sihyun-yu/REPA#3]
Hello, thanks for the interesting work. It inspire us to explore the relationship between the generative model e.g. diffusion model and the discriminative model e.g. DINOv2 within the intermediate layers. Absolutely, it's a meaningful work. I wonder if the author will release their model's checkpoint on ImageNet dataset, so that we can develop some extension work based on it.

**Comment by sihyun-yu** [comment]
Hi, we already released the checkpoint (please read "evaluation" section in README or see [here](https://github.com/sihyun-yu/REPA/blob/9d60489e823bd9b356319b6d30e4cf7f333119a9/utils.py#L22) for the link.

**Comment by nachifur** [comment]
> Hi, we already released the checkpoint (please read "evaluation" section in README or see [here](https://github.com/sihyun-yu/REPA/blob/9d60489e823bd9b356319b6d30e4cf7f333119a9/utils.py#L22) for the link).

Hello, thanks for the interesting work. 

The download link does not work. Can you provide a new link?

**Comment by sihyun-yu** [comment]
@nachifur it still works for me. Could you try again with the wget command?

**Comment by nachifur** [comment]
> @nachifur it still works for me. Could you try again with the wget command?

Thank you for your quick reply. It was a problem with my internet and it's fine now.
