### ISSUE TITLE
CFG and Convergence

### ISSUE THREAD

**Issue by kayson-tihoi** [sihyun-yu/REPA#4]
Hi,

Thanks for your awesome work!!!

May I ask the convergence under other cfg scales? Your results demonstrate model divergence without CFG. In my experiments, I observed that even with FID margin at CFG=1.0 (which is equivalent to no guidance), the optimal performance remains relatively similar across scales.

![image](https://github.com/user-attachments/assets/56b0dddc-57cd-410b-96d4-806e3cbc98aa)

**Comment by sihyun-yu** [comment]
Hi, thanks for your interest! Are you asking for FID curve with respect to training iteration with cfg?

**Comment by kayson-tihoi** [comment]
Thanks for your quick reply!

Take the result as an example. If we were to traverse various CFG scales to identify the optimal FID, what would be the observed gap? In other words, different models trained under various settings might prefer different scales - some favoring larger scales, others smaller ones. I'm particularly interested in understanding how these training recipes affect both the optimal scale and the resulting optimal FID. And whether the FID w/o CFG can really reflect the model convergence. :-)

<img width="393" alt="image" src="https://github.com/user-attachments/assets/99e7475e-6a9b-40f9-8c29-73767f19456e">

**Comment by sihyun-yu** [comment]
Thanks for the clarification. My experience is that REPA still shows considerable improvement w/ cfg (see Table 2 for an example). I have not taken analysis in how the optimal coefficient becomes different --- according to my experience it seems the optimal cfg value is quite to the original DiT/SiTs.  Also I think exploring whether the FID w/o CFG can really reflect the model convergence is an important and interesting future direction!
