### ISSUE TITLE
Exploring alignment with multiple models?

### ISSUE THREAD

**Issue by elicassion** [sihyun-yu/REPA#8]
Hi @sihyun-yu ,

Great work! 

I've also been working on taking advantage of pre-trained visual representations to supervise a model for a different task. 
Here is our work [Theia](https://github.com/bdaiinstitute/theia) to improve visual representation for robot learning. I also want to mention NVIDIA's work [RADIO](https://github.com/NVlabs/RADIO), which solves vision problems.

Both approaches use multiple teacher models and we found this improves the representation a lot. I also noticed that you have implemented the [multi-teacher training](https://github.com/sihyun-yu/REPA/blob/9d60489e823bd9b356319b6d30e4cf7f333119a9/train.py#L295) in your codebase. Did you explore this aspect and would you mind sharing your observations if you had?

**Comment by sihyun-yu** [comment]
Hi, thanks for your interest! We have tried in the early experiments but unfortunately we did not get more improvements --- but they were very initial experiments so I would not be sure if it is not beneficial in our case. Exploring this direction will be an interesting direction! And thanks for introducing some works; I will take a look.
